name: React CI

on:
  push:
   branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '20'
      
      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npx test
      
      - name: Build
        run: npm run build
    
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npx test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
        
      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npx test

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Login to Vercel
        run: vercel login --token${{ secrets.s0w5B1oVAqtJT8pqGElZ4ocJ }}

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment-preview --token=${{ secrets.s0w5B1oVAqtJT8pqGElZ4ocJ }}
      
      - name: Build Projects Artifacts
        run: verce; build --token=${{ secrets.s0w5B1oVAqtJT8pqGElZ4ocJ }}
      
      - name: Deploy Projects Artifacts to Vercel
        run: vercel deploy --prebuild --token=${{ secrets.s0w5B1oVAqtJT8pqGElZ4ocJ }} --prod